import './globals.css'
import { DM_Sans } from 'next/font/google';
// import { Inter } from 'next/font/google'

const dmSans = DM_Sans({
  weight: ['400', '500', '700',],
  style: 'normal',
  subsets: ['latin', 'latin-ext']
});

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Alviss Raghnall Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className}`}>{children}</body>
      
    </html>
  )
}
